const VALIDATION_ERROR = 400;
const AUTH_ERROR = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICT_ERROR = 409;
const DEFAULT_ERROR = 500;

module.exports = {
  VALIDATION_ERROR,
  AUTH_ERROR,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT_ERROR,
  DEFAULT_ERROR,
};
